version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_dev
    stdin_open: true
    tty: true
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - CONTAINER_TYPE=app
